name = "TextUserInterfaces"
uuid = "2a09ff82-1be9-11e9-2ab7-19964783a84b"
authors = ["Ronan Arraes Jardim Chagas <ronisbr@gmail.com>"]
version = "0.0.1"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[compat]
julia = "â‰¥ 1.0.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
