name = "TextUserInterfaces"
uuid = "2a09ff82-1be9-11e9-2ab7-19964783a84b"
version = "0.1.1"
authors = ["Ronan Arraes Jardim Chagas <ronisbr@gmail.com>"]

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FileWatching = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Ncurses_jll = "68e3532b-a499-55ff-9963-d1c0c0748b3a"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StringManipulation = "892a3eda-7b42-436c-8928-eab12a02cf0e"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
Colors = "0.13.1"
Dates = "1"
FileWatching = "1"
Libdl = "1"
LinearAlgebra = "1"
Ncurses_jll = "6.5.1"
PrecompileTools = "1"
Reexport = "1.2.2"
StringManipulation = "0.4.2"
UnPack = "1"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
